defineUser("rster2002");
defineShop("rster2002", "Paarden shop", "overworld: x: -111 z: -234");
defineItem("rster2002", "Paarden shop", "Paard speed 1", "1", "3", null);
defineItem("rster2002", "Paarden shop", "Paard speed 2", "1", "6", null);
defineItem("rster2002", "Paarden shop", "Paard speed 3", "1", "10", null);
defineItem("rster2002", "Paarden shop", "Paard speed 4", "1", "15", null);
defineItem("rster2002", "Paarden shop", "Paard speed 5", "1", "20", null);
defineUser("Luuk_T");
defineShop("Luuk_T", "Elytra shop", "overworld: x: -72 z: -1390");
defineItem("Luuk_T", "Elytra shop", "elytra", "1", "20", null);